### ISSUE TITLE
Android 13: crash on start

### ISSUE THREAD

**Issue by AeliusSaionji** [warren-bank/Android-AirPlay-Client#3]
```log
FATAL EXCEPTION: main
Process: com.github.warren_bank.airplay_client, PID: 27481
java.lang.RuntimeException: Unable to create service com.github.warren_bank.airplay_client.service.NetworkingService: java.lang.IllegalArgumentException: com.github.warren_bank.airplay_client: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4539)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:346)
	at android.os.Looper.loop(Looper.java:475)
	at android.app.ActivityThread.main(ActivityThread.java:7954)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalArgumentException: com.github.warren_bank.airplay_client: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:753)
	at android.app.PendingIntent.getService(PendingIntent.java:715)
	at com.github.warren_bank.airplay_client.service.NetworkingService.getPendingIntent_StopService(Unknown Source:15)
	at com.github.warren_bank.airplay_client.service.NetworkingService.getNotification(Unknown Source:56)
	at com.github.warren_bank.airplay_client.service.NetworkingService.showNotification(Unknown Source:4)
	at com.github.warren_bank.airplay_client.service.NetworkingService.onCreate(Unknown Source:104)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4526)
	... 9 more
```

**Comment by warren-bank** [comment]
good stuff..
annoying, that every version of Android breaks some aspect of user space..
but I do appreciate your letting me know about this..
I'll add the necessary flag to the pending Intent and publish an updated release..
probably by tomorrow.

**Comment by warren-bank** [comment]
release [v0.5.3](https://github.com/warren-bank/Android-AirPlay-Client/releases/tag/v0.5.3) is tested on Android 13 (LineageOS 20)..
the past few versions of Android all presented new obstacles..
this update addresses them all together at once.

now, I'll need to do the same for all of my other Android apps (that run foreground services)..
should I be upset with you? :smiley:

sorry for the delay in pushing this update..
I got sidetracked by wanting to install LineageOS on a device running a stock ROM..
it got a little sketchy (unlocking its bootloader), but worked out in the end.

anyway, thanks again for letting me know that updates were needed.

**Comment by AeliusSaionji** [comment]
Thanks! Yeah it seems like this particular permission on 13 has hit a bunch of apps 🙃 

Glad you were able to sort it out

**Comment by warren-bank** [comment]
Just a quick heads up..
I found a small bug that was related to the previous commit..
so I chose to rewrite history..
amend the commit, and replace the APKs for this recent release.

If you use the app, you might want to update (again).
This update prevents a crash if trying to navigate up ("..") into a directory that is inaccessible.
Now, it just show an empty directory.
